### ISSUE TITLE
planilla de costos

### ISSUE THREAD

**Issue by LucasNatoli** [LucasNatoli/dht11#4]
documentar costos de los componentes electronicos

**Comment by LucasNatoli** [comment]
aca va la de infrastructura cloud
https://docs.google.com/spreadsheets/d/1atsvPpmu3npeZKyNZyE_5j5sL2h09jreh2owBDso8L0/edit?usp=sharing

**Comment by damiansicaro** [comment]
Aca va la planilla de costos del material electronico que tenemos actualmente: https://docs.google.com/spreadsheets/d/1Mm_VAf3L9kzMtvn40R0wIHcy31R7o0lFDqXDtAroUhs/edit?usp=sharing

**Comment by damiansicaro** [comment]
A la planilla de infrastructura cloud hay que agregarle costo del registro de dominio

**Comment by LucasNatoli** [comment]
eso depende mucho del nombre, como vimos ayer puede ir de 30$ a 458$ anuales. 
Con ivan estamos cobrando 9dolares anuales por registro de .com salvo que la direccion sea muy cara. Si sirve como dato lo anoto.

**Comment by damiansicaro** [comment]
Dale si anotalo que sirve como dato

**Comment by LucasNatoli** [comment]
listo, cierro el issue y cualquier novedad se actualiza en las planillas
